package com.studybuddy.services;

import com.studybuddy.dao.NoteDAO;
import com.studybuddy.models.Note;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Service layer for Note operations.
 * FIXED: Now delegates all database calls to NoteDAO instead of
 * running its own JDBC queries directly (which had wrong column names).
 *
 * Architecture: Controller → NoteService → NoteDAO → DatabaseConnection → SQL Server
 */
public class NoteService {

    private final NoteDAO noteDAO = new NoteDAO();

    // =========================
    // GET NOTES BY USER
    // =========================

    /**
     * Returns all notes for the given user from the database.
     * Delegates to NoteDAO which uses correct SQL column names.
     * SQL: SELECT * FROM Notes WHERE userId = ? ORDER BY uploadDate DESC
     */
    public List<Note> getNotesByUserId(int userId) throws SQLException {
        return noteDAO.getNotesByUserId(userId);
    }

    // =========================
    // GET ALL PUBLIC NOTES
    // =========================

    /**
     * Returns all public (non-private) notes.
     * Used by DashboardService for community notes section.
     * SQL: SELECT * FROM Notes WHERE isPrivate = 0 ORDER BY uploadDate DESC
     */
    public List<Note> getAllPublicNotes() throws SQLException {
        return noteDAO.getAllPublicNotes();
    }

    // =========================
    // GET RECENT NOTES
    // =========================

    /**
     * Returns the most recent public notes up to the given limit.
     */
    public List<Note> getRecentNotes(int limit) throws SQLException {
        return noteDAO.getRecentNotes(limit);
    }

    // =========================
    // SEARCH NOTES
    // =========================

    /**
     * Searches public notes by keyword and/or subject.
     */
    public List<Note> searchPublicNotes(String query, String subject) throws SQLException {
        return noteDAO.searchPublicNotes(query, subject);
    }

    // =========================
    // CREATE NOTE
    // =========================

    /**
     * Saves a new note to the database.
     * Delegates to NoteDAO.createNote() which uses correct column names
     * and does NOT include id (auto-generated by SQL Server IDENTITY).
     */
    public void createNote(Note note) throws SQLException {
        noteDAO.createNote(note);
    }

    // =========================
    // DELETE NOTE
    // =========================

    /**
     * Deletes a note by its integer ID.
     */
    public void deleteNote(int id) throws SQLException {
        noteDAO.deleteNote(id);
    }

    // =========================
    // COUNT NOTES BY USER
    // =========================

    /**
     * Returns the total note count for a user.
     * SQL: SELECT COUNT(*) FROM Notes WHERE userId = ?
     */
    public int countNotesByUser(int userId) {
        try {
            return noteDAO.countNotesByUser(userId);
        } catch (SQLException e) {
            e.printStackTrace();
            return 0;
        }
    }
}