package com.studybuddy.services;

import com.studybuddy.dao.NoteDAO;
import com.studybuddy.dao.SubjectDAO;
import com.studybuddy.models.Note;
import com.studybuddy.models.User;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Service layer for Note operations.
 * FIXED: Now delegates all database calls to NoteDAO instead of
 * running its own JDBC queries directly (which had wrong column names).
 *
 * Architecture: Controller → NoteService → NoteDAO → DatabaseConnection → SQL Server
 */
public class NoteService {

    private final NoteDAO    noteDAO    = new NoteDAO();
    private final SubjectDAO subjectDAO = new SubjectDAO();

    // =========================
    // GET NOTES BY USER
    // =========================

    /**
     * Returns all notes for the given user from the database.
     * Delegates to NoteDAO which uses correct SQL column names.
     * SQL: SELECT * FROM Notes WHERE userId = ? ORDER BY uploadDate DESC
     */
    public List<Note> getNotesByUserId(int userId) throws SQLException {
        return noteDAO.getNotesByUserId(userId);
    }

    // =========================
    // GET ALL PUBLIC NOTES
    // =========================

    /**
     * Returns all public (non-private) notes.
     * Used by DashboardService for community notes section.
     * SQL: SELECT * FROM Notes WHERE isPrivate = 0 ORDER BY uploadDate DESC
     */
    public List<Note> getAllPublicNotes() throws SQLException {
        return noteDAO.getAllPublicNotes();
    }

    // =========================
    // GET RECENT NOTES
    // =========================

    /**
     * Returns the most recent public notes up to the given limit.
     */
    public List<Note> getRecentNotes(int limit) throws SQLException {
        return noteDAO.getRecentNotes(limit);
    }

    // =========================
    // SEARCH NOTES
    // =========================

    /**
     * Searches public notes by keyword and/or subject.
     */
    public List<Note> searchPublicNotes(String query, String subject) throws SQLException {
        return noteDAO.searchPublicNotes(query, subject);
    }

    // =========================
    // CREATE NOTE
    // =========================

    /**
     * Saves a new note to the database.
     * Delegates to NoteDAO.createNote() which uses correct column names
     * and does NOT include id (auto-generated by SQL Server IDENTITY).
     */
    public void createNote(Note note, boolean autoApprove) throws SQLException {
        noteDAO.createNote(note, autoApprove);
    }

    public int createNoteWithFile(Note note, File file, boolean autoApprove) throws SQLException, IOException {
        if (noteDAO.duplicateExists(note.getTitle(), note.getUserId(), null)) {
            throw new IllegalArgumentException("A note with this title already exists.");
        }
        FileStorageService storage = FileStorageService.getInstance();
        if (file != null) {
            String storedPath = storage.storeFile(file, "notes");
            note.setFilePath(storedPath);
            note.setFileName(file.getName());
            String ext = file.getName().contains(".")
                    ? file.getName().substring(file.getName().lastIndexOf('.') + 1).toUpperCase()
                    : "TXT";
            note.setFileType(ext);
        }
        noteDAO.createNote(note, autoApprove);
        return note.getId();
    }

    public boolean updateNote(Note note) throws SQLException {
        return noteDAO.updateNote(note);
    }

    public Note getNoteById(int id) throws SQLException {
        return noteDAO.getNoteById(id);
    }

    public boolean deleteNoteWithFile(int id, User user) throws SQLException {
        Note note = noteDAO.getNoteById(id);
        if (note == null) return false;
        AuthorizationService.getInstance().requireOwnership(user, note.getUserId());
        FileStorageService.getInstance().deleteFile(note.getFilePath());
        noteDAO.hardDeleteNote(id);
        return true;
    }

    public void incrementDownloads(int noteId) throws SQLException {
        noteDAO.incrementDownloads(noteId);
    }

    // =========================
    // DELETE NOTE
    // =========================

    /**
     * Deletes a note by its integer ID.
     */
    public void deleteNote(int id) throws SQLException {
        noteDAO.deleteNote(id);
    }

    // =========================
    // COUNT NOTES BY USER
    // =========================

    /**
     * Returns the total note count for a user.
     * SQL: SELECT COUNT(*) FROM Notes WHERE userId = ?
     */
    public int countNotesByUser(int userId) {
        try {
            return noteDAO.countNotesByUser(userId);
        } catch (SQLException e) {
            e.printStackTrace();
            return 0;
        }
    }
    /**
     * Returns a flat list of all active subject names from the canonical Subjects table.
     * Used to populate the Notes subject-filter ComboBox without coupling NotesController
     * to the Questions domain.  Falls back gracefully on DB failure.
     */
    public List<String> getAllSubjectNames() {
        try {
            return subjectDAO.getAllActiveSubjects().stream()
                    .map(com.studybuddy.models.Subject::getName)
                    .sorted()
                    .collect(Collectors.toList());
        } catch (Exception e) {
            System.err.println("[NoteService] getAllSubjectNames failed: " + e.getMessage());
            return new ArrayList<>();
        }
    }
}